server:
  port: ${PORT:9011}
  servlet:
    context-path: /

spring:
  application:
    name: Drill
#  thymeleaf:
#    cache: false
#    prefix: classpath:templates/
#    suffix: .html
#    check-template-location: true
#    mode: HTML
#    order: 0
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: html/
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

logging:
  level:
    root: info
    com:
      example: debug