# server
server:
  port: ${PORT:9011}
  servlet:
    context-path: /
# spring
spring:
  application:
    name: Drill
#  thymeleaf:
#    cache: false
#    prefix: classpath:templates/
#    suffix: .html
#    check-template-location: true
#    mode: HTML
#    order: 0
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: html/
  web:
    resources:
      static-locations: classpath:/static/

  datasource:
    url: jdbc:mariadb://localhost:3306/drill
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  devtools:
    livereload:
      enabled: true

# logging
logging:
  level:
    root: info
    com:
      example: debug