# spring, https://luvstudy.tistory.com/130
spring:
  config:
    use-legacy-processing: true
#    import: "optional:configserver:http://localhost:8888"
  application:
    name: drill
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh

---

# server
server:
  port: ${PORT:9011}
  servlet:
    context-path: /
# spring
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: drill
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: html/
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create

# logging
logging:
  level:
    root: info
    com:
      example: debug

#properties
drill:
  test-schedule-period: 0/10 * * * * *
