spring:
  application:
    name: drill
management:
  endpoints:
    web:
      exposure:
        include: refresh

---

# server
server:
  port: ${PORT:9011}
  servlet:
    context-path: /
# spring
spring:
  config:
    activate:
      on-profile: dev
    use-legacy-processing: true
  application:
    name: drill
  mvc:
    view:
      prefix: html/
      suffix: .html
  webflux:
    base-path:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

# logging
logging:
  level:
    root: info
    com:
      example: debug
      zaxxer:
        hikari:
          pool:
            HikariPool: debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: debug
      connection: info

#properties
drill:
  test-schedule-period: "-"