# server
server:
  port: ${PORT:9011}
  servlet:
    context-path: /
# spring
spring:
  application:
    name: drill
  redis:
    host: 192.168.0.172
    port: 6379
    lettuce:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 2
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info
    com:
      example: info

