# spring, https://luvstudy.tistory.com/130
spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: drill
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh
