# spring, https://luvstudy.tistory.com/130
spring:
  application:
    name: drill

---

# server
server:
  port: ${PORT:9011}
  servlet:
    context-path: /
# spring
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: drill
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
    host: 192.168.0.172
    port: 6379
    lettuce:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 2

# logging
logging:
  level:
    root: info
    com:
      example: debug

