# server
server:
  port: ${PORT:9011}
  servlet:
    context-path: /
# spring
spring:
  application:
    name: drill
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: html/
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

# logging
logging:
  level:
    root: info
    com:
      example: debug

#properties
drill:
  test-schedule-period: 1 * * * * *