server:
  port: ${POST:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/djkim1013/spring-practice.git
          default-label: djkim
          search-paths: config
          skip-ssl-validation: true
          username: djkim1013
          password: 3starnzer0
management:
  endpoints:
    web:
      exposure:
        include: refresh