server:
  port: ${POST:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/djkim1013/spring_practice.git
          skip-ssl-validation: true
          default-label: djkim
management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
    shutdown:
      enabled: true