server:
  port: ${POST:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/gram/IdeaProjects/drill/config
management:
  endpoints:
    web:
      exposure:
        include: refresh